#!/usr/bin/env bash
set -euo pipefail

mkdir -p docs

echo "[Verify] pytest (fast subset)..." | tee docs/VERIFY_RUN.txt
# You may replace/extend with your project’s canonical targets.
# Keeping it bounded and self-terminating:
pytest -q 2>&1 | tee -a docs/VERIFY_RUN.txt

echo "[Snapshot] writing SYSTEM_FULL_SNAPSHOT.md (placeholder)..." | tee -a docs/VERIFY_RUN.txt
# If your repo has a canonical snapshot generator script, call it here instead.
# Example:
# python scripts/gen_snapshot.py > docs/SYSTEM_FULL_SNAPSHOT.md
date > docs/SYSTEM_FULL_SNAPSHOT.md
echo "Snapshot placeholder generated by .agent/skills/evidence/snapshot-generator/skill.sh" >> docs/SYSTEM_FULL_SNAPSHOT.md
