#!/usr/bin/env python3
"""
Season Freeze with Manifest – Phase 3B.

Freeze a season with deterministic manifest referencing universe, dataset,
strategy spec, plateau report, and chosen parameters.

Usage:
    python scripts/freeze_season_with_manifest.py --season 2026Q1 [--force]

If season directory already contains plateau report and governance artifacts,
the script will automatically locate them.

Alternatively, you can specify each input file explicitly.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Add src to path
src_dir = Path(__file__).parent.parent / "src"
sys.path.insert(0, str(src_dir))

from core.season_state import freeze_season as core_freeze_season
from core.season_context import season_dir, outputs_root
from governance.freezer import freeze_season as governance_freeze_season
from governance.models import FreezeContext


def locate_default_paths(season: str) -> dict:
    """
    Attempt to locate default input files for a given season.
    Returns a dict of Paths.
    """
    sdir = season_dir(season)
    root = Path(outputs_root())

    # Universe spec (global)
    universe_candidates = [
        Path("configs/portfolio/instruments.yaml"),
        Path("configs/universe.yaml"),
        root / "universe.yaml",
    ]
    universe_path = None
    for cand in universe_candidates:
        if cand.exists():
            universe_path = cand
            break
    if universe_path is None:
        raise FileNotFoundError("Could not locate universe definition file")

    # Dataset registry
    dataset_registry_path = root / "datasets" / "datasets_index.json"
    if not dataset_registry_path.exists():
        # Fallback to older location
        dataset_registry_path = root / "datasets_index.json"
        if not dataset_registry_path.exists():
            raise FileNotFoundError("Could not locate dataset registry")

    # Strategy spec (content-addressed ID) – we need a JSON file.
    # Look for strategy manifest generated by the registry.
    strategy_spec_path = root / "strategies" / "strategy_manifest.json"
    if not strategy_spec_path.exists():
        # Fallback to built-in strategy spec dump (maybe not present)
        # For now, we'll require explicit path.
        strategy_spec_path = None

    # Plateau report and chosen params (should be in season/governance/plateau)
    plateau_dir = sdir / "governance" / "plateau"
    plateau_report_path = plateau_dir / "plateau_report.json"
    chosen_params_path = plateau_dir / "chosen_params.json"

    return {
        "universe_path": universe_path,
        "dataset_registry_path": dataset_registry_path,
        "strategy_spec_path": strategy_spec_path,
        "plateau_report_path": plateau_report_path,
        "chosen_params_path": chosen_params_path,
    }


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Freeze a season with deterministic manifest"
    )
    parser.add_argument(
        "--season",
        required=True,
        help="Season identifier (e.g., '2026Q1')"
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Allow overwriting existing frozen season (dangerous)"
    )
    parser.add_argument(
        "--universe",
        type=Path,
        help="Path to universe definition YAML (default: auto-detect)"
    )
    parser.add_argument(
        "--dataset-registry",
        type=Path,
        help="Path to dataset registry JSON (default: auto-detect)"
    )
    parser.add_argument(
        "--strategy-spec",
        type=Path,
        help="Path to strategy spec JSON (default: auto-detect)"
    )
    parser.add_argument(
        "--plateau-report",
        type=Path,
        help="Path to plateau_report.json (default: season/governance/plateau/plateau_report.json)"
    )
    parser.add_argument(
        "--chosen-params",
        type=Path,
        help="Path to chosen_params.json (default: season/governance/plateau/chosen_params.json)"
    )
    parser.add_argument(
        "--engine-version",
        default="unknown",
        help="Engine version identifier (default: unknown)"
    )
    parser.add_argument(
        "--notes",
        default="",
        help="Optional notes for the season manifest"
    )

    args = parser.parse_args()

    # Determine input paths
    try:
        defaults = locate_default_paths(args.season)
    except FileNotFoundError as e:
        print(f"Error locating default files: {e}", file=sys.stderr)
        print("Please specify explicit paths using command line arguments.", file=sys.stderr)
        return 1

    universe_path = args.universe or defaults["universe_path"]
    dataset_registry_path = args.dataset_registry or defaults["dataset_registry_path"]
    strategy_spec_path = args.strategy_spec or defaults["strategy_spec_path"]
    plateau_report_path = args.plateau_report or defaults["plateau_report_path"]
    chosen_params_path = args.chosen_params or defaults["chosen_params_path"]

    # Validate required files exist
    missing = []
    for name, path in [
        ("universe", universe_path),
        ("dataset registry", dataset_registry_path),
        ("strategy spec", strategy_spec_path),
        ("plateau report", plateau_report_path),
        ("chosen params", chosen_params_path),
    ]:
        if path is None or not path.exists():
            missing.append(f"{name}: {path}")
    if missing:
        print("Missing required input files:", file=sys.stderr)
        for m in missing:
            print(f"  - {m}", file=sys.stderr)
        return 1

    # Step 1: Freeze the season (core state)
    print(f"Freezing season '{args.season}'...")
    try:
        core_state = core_freeze_season(
            season=args.season,
            by="cli",
            reason="Freeze with manifest",
            create_snapshot=True,
        )
        print(f"  Season state marked as FROZEN.")
    except Exception as e:
        print(f"Error freezing season state: {e}", file=sys.stderr)
        if not args.force:
            return 1
        print("  Continuing with manifest creation due to --force.", file=sys.stderr)

    # Step 2: Create SeasonManifest
    print("Creating SeasonManifest...")
    ctx = FreezeContext(
        universe_path=universe_path,
        dataset_registry_path=dataset_registry_path,
        strategy_spec_path=strategy_spec_path,
        plateau_report_path=plateau_report_path,
        chosen_params_path=chosen_params_path,
        engine_version=args.engine_version,
        notes=args.notes,
        season_id=args.season,
    )

    try:
        manifest = governance_freeze_season(ctx, force=args.force)
        print(f"  SeasonManifest saved to {manifest.season_id}")
    except Exception as e:
        print(f"Error creating SeasonManifest: {e}", file=sys.stderr)
        return 1

    # Step 3: Verify integrity (optional)
    print("Season freeze completed successfully.")
    print(f"  Season ID: {args.season}")
    print(f"  Universe hash: {manifest.universe_ref[:16]}...")
    print(f"  Dataset hash: {manifest.dataset_ref[:16]}...")
    print(f"  Strategy spec hash: {manifest.strategy_spec_hash[:16]}...")
    print(f"  Plateau hash: {manifest.plateau_ref[:16]}...")
    print(f"  Timestamp: {manifest.timestamp}")

    return 0


if __name__ == "__main__":
    sys.exit(main())